name: Nusagraha
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  # State Management
  provider: ^6.1.1
  # Navigation
  go_router: ^13.2.0
  # Local Storage
  shared_preferences: ^2.2.2
  # HTTP Client
  http: ^1.1.2
  # Form Validation
  form_validator: ^2.1.1
  # Animation
  lottie: ^3.1.2
  # URL Launcher
  url_launcher: ^6.2.5
  # Device Info
  device_info_plus: ^10.1.0
  # Image Picker
  image_picker: ^1.0.4
  # Permission Handler
  permission_handler: ^11.0.1
  # PDF Viewer
  flutter_pdfview: ^1.3.2
  # Path Provider
  path_provider: ^2.1.1
  # Local Notifications
  flutter_local_notifications: ^17.2.2
  # Open Files
  open_file: ^3.3.2
  # Skeletonizer
  skeletonizer: ^2.1.0+1
  # WebView
  webview_flutter: ^4.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/lottie/
    - assets/tempt.pdf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon-nusagraha.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon-nusagraha.png"
